name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Any bugreport helps us to improve Diesel.
  - type: input
    label: Rust Version
    description: The Rust version required to reproduce the bug. You can usually get that version by using `rustc --version` in your project directory.
    placeholder: 1.89.0
    validation:
        required: true
    
  - type: textarea
    id: problem-description
    attributes:
      label: What happened?
      description: Describe wh
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please include as much of your codebase as needed to reproduce the error.  If the relevant files are large, please consider linking to a public repository or a [Gist](https://gist.github.com/). This includes normally the following parts:
      render: rust
  - type: checkboxes
    id: Checklist
    attributes:
      label: Checklist
      description: 
      options:
        - label: |
            I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
        - label: This issue can be reproduced on Rust's stable channel. (Please submit the issue in the Rust issue tracker instead if that's not the case)
        - label: This issue can be reproduced without requiring a third party crate
